---
glob: 'app/**/*.erb'

EnableDefaultLinters: true

linters:
  AllowedScriptType:
    enabled: true
    allow_blank: false
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Layout/FirstArgumentIndentation:
        Enabled: true
        EnforcedStyle: consistent
