# Kustomization file
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demoapp

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - deployment-app.yaml
  - deployment-sidekiq.yaml
  - pdb-app.yaml
  - pdb-sidekiq.yaml
