# Build image from every merge to main or with a build tag.
name: Build image

on:
  push:
    branches:
      - main
    tags:
      - build/**

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  # HACK: remove
  REPOSITORY_DOWNCASED: briansigafoos/docker-rails-webpacker-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Required for cache-from and cache-to support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          secrets: "rails_master_key=${{ secrets.RAILS_MASTER_KEY }}"
          tags: ${{ inputs.package }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY_DOWNCASED }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY_DOWNCASED }}:buildcache,mode=max
          # TODO: switch to type=gha caching once it works/is stable.
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
