# Build image and push to Github Container Registry
#
# Built via example in Github docs and links below from docker/... actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
name: Build image

on:
  push:
    # branches:
      # - master
      # - main
    tags:
      - build/**

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}

      # https://github.com/docker/build-push-action
      # TODO: confirm and fix caching!
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "rails_master_key=${{ secrets.RAILS_MASTER_KEY }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
